variables:
  POSTGRES_DB: weng-issue-tracker-test
  DATABASE_URL: "postgresql://postgres@postgres:5432/weng-issue-tracker-test"

before_script:
  - apt-get update -y
  - apt-get install openjdk-8-jre postgresql-client -y
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - export LEIN_ROOT=1
  - PATH=$PATH:.
  - lein deps
  - lein migratus migrate

test: 
  script: 
    - lein test
